### ISSUE TITLE
上司に💩を送り付ける機能の提案

### ISSUE THREAD

**Issue by tobynet** [arigato-java/JavaButton#11]
ジャバボタンを押下するたびに、あらかじめ連携した Twitter アカウントから上司のアカウントへ 💩関連ツイートを送り付ける。
(もしくは、ただ「上司に💩を投げつけた」と投稿する。)

ツイートは連投可能なように、毎回、重複しない文面を生成する。

## 文脈

> 例えば、8時間労働において、4時間を集中して過ごしたとする。残り4時間はどうするものだろうか。喫煙室、雑談、早弁、Python 2.7 から Go言語のトランスレータを作る、ジャバボタン連打… etc。 私はこう過ごしているというご意見、FAXをお待ちしております。
https://twitter.com/toby_net/status/827073566159966208

> @toby_net 上司にうんこ投げつける妄想をする、ジャバボタンを押す、ジャバボタンに押される、ジャバボタンを探す、ジャバボタンを考える等が考えられます。
https://twitter.com/arclisp/status/827076161867886592

> @arclisp 上司に💩投げつけるのいいですね。1日2時間くらいは💩投げつけてみたいと思います。ジャバのお気遣いにも感謝、ありがとうございました。
https://twitter.com/toby_net/status/827077123202363394

> @toby_net それはそれとして、ジャバボタンを押すと上司にうんこが投げつけられる構造が一番シンプルだと思ったんですがどうでしょうか。
https://twitter.com/arclisp/status/827077402547204104

**Comment by tomari** [comment]
あなたは「ジャバ病」です。日常生活がジャバのダウンロードに依存しており、それが原因で社会との軋轢を感じていませんか。DSM-5によると、ジャバ病は以下のような基準で診断されます。

* ジャバを過剰にダウンロードする
  * 100 Gb/s以上のトラフィックを5分以上発生させる
  * または月間50 TBを超えるトラフィックを継続的に発生させる (100 Mbps前後に換算されます)
* ジャバスポットへの「巡礼行為」が見られる
* ジャバが無料でダウンロードできることを殊更に強調した格好で外出する
* 発言が不安定になり、ジャバを連呼することがしばしばある

今回のご相談である(ノッジャバ)を投げつける、という行為ではあなたとジャバと社会との間の軋轢を解消することにはなりません。ジャバ病の完治には適切な治療が必要になります。まずは、行政のジャバ関連の施設に相談してみてください。

**Comment by tomari** [comment]
開発チーム内で話し合ったのですが、この機能を実装した場合Apple/Googleの審査を通過しない可能性が高いことから実装しない方針になりました。ただし、同等の機能を内部ツールのInvoke-JavaRequest (PowerShell cmdlet)で実現可能であるため、こちらを公開することができないかの検討を行います。

**Comment by tomari** [comment]
FYI: https://akiba-pc.watch.impress.co.jp/docs/news/news/1125358.html
