### ISSUE TITLE
アドベンチャーパートのストーリー

### ISSUE THREAD

**Issue by tomari** [arigato-java/JavaButton#12]
【あらすじ】異世界で目を覚ました主人公は、手元端末でSSLのHandshakeが失敗する原因がタイムリープしてしまったことであることに気づく。異世界で出会った仲間とともに猟奇事件を捜査する中、異世界と元の世界との接点、そして失われたジャバの秘密を解き明かしていく。

**Comment by tobynet** [comment]
「大丈夫ですか？」

キンキンとした声が頭に響く。頭が痛い。目を開けると、アフロの女が俺を覗いていた。
女は自らを「アフロディーテ」と名乗った。

「…アフロと呼んでください」。
「アフ、ロ…？」 。 俺は思わず「ジャバじゃないのか」と返しそうになる言葉を飲み込んだ。

ここはどこだ。体を少し起こし、辺りを見渡した。少なくとも、元いたダウンロードセンターではない。そうだ。たしか、俺は50連勤を決めたあと、今日5本目のエナジードリンクを開け、その後に意識が遠のき…。

まさか、ここは、サーバーの中だろうか！  あまりに、ジャバしすぎたため、センターのサーバーと一体化したのではなかろうか。 もしそうであれば、我々は念願のジャバと意識を共有することに一歩近づき…

ふと「大丈夫ですか？」という声を思い出し、俺は現実に引き戻された。

「アフロさん、でしたか。ここはどこなのでしょうか」。
「…？ ここは、ダウンロードサーバー≪東日本リージョン≫と呼ばれています」。

間違いない。働きすぎで、俺の頭はどうにかなったのだ。

**Comment by tomari** [comment]
一応方針なんですが、ストーリーは分岐させる予定です。erbっぽい感じのDSLでスクリプト中でステート管理できるようにしたいと思っています。多言語対応はどうやるのがよいのか検討中。

**Comment by tomari** [comment]
アンリアル版の方でノベル関係のアセット実装を大枠で行いました。
ノベルはツールからJSONで吐き出して、Unrealに読み込む形になります。
https://github.com/arigato-java/UnrealJavaButton/blob/master/NovelSource/TestChapter.javason

実装についてのイシューは項目ごとに分けたいので、このイシューは一旦クローズします。
