### ISSUE TITLE
ジャバボタンの画像にノイズがある

### ISSUE THREAD

**Issue by yukkurisinai** [arigato-java/JavaButton#9]
https://github.com/arigato-java/JavaButton/blob/studio/app/src/main/res/drawable-xxhdpi/dl_button.png

右端
ウィジェットで設置すると地味に気になるので消したい

**Comment by tomari** [comment]
グラフィックデザイナーに修正してもらいました
ｺﾞｶｸﾆﾝ https://github.com/arigato-java/JavaButton/pull/10
